// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sample.proto

package sample

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HelloType int32

const (
	HelloType_NONE HelloType = 0
	HelloType_ANY  HelloType = 1
)

var HelloType_name = map[int32]string{
	0: "NONE",
	1: "ANY",
}
var HelloType_value = map[string]int32{
	"NONE": 0,
	"ANY":  1,
}

func (x HelloType) String() string {
	return proto.EnumName(HelloType_name, int32(x))
}
func (HelloType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_sample_bf826917c026f783, []int{0}
}

type Error struct {
	ErrorMessage         string   `protobuf:"bytes,1,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_sample_bf826917c026f783, []int{0}
}
func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (dst *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(dst, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

type Hello struct {
	Name                 string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 HelloType `protobuf:"varint,2,opt,name=type,proto3,enum=sample.HelloType" json:"type,omitempty"`
	Messages             []string  `protobuf:"bytes,3,rep,name=messages,proto3" json:"messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Hello) Reset()         { *m = Hello{} }
func (m *Hello) String() string { return proto.CompactTextString(m) }
func (*Hello) ProtoMessage()    {}
func (*Hello) Descriptor() ([]byte, []int) {
	return fileDescriptor_sample_bf826917c026f783, []int{1}
}
func (m *Hello) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hello.Unmarshal(m, b)
}
func (m *Hello) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hello.Marshal(b, m, deterministic)
}
func (dst *Hello) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hello.Merge(dst, src)
}
func (m *Hello) XXX_Size() int {
	return xxx_messageInfo_Hello.Size(m)
}
func (m *Hello) XXX_DiscardUnknown() {
	xxx_messageInfo_Hello.DiscardUnknown(m)
}

var xxx_messageInfo_Hello proto.InternalMessageInfo

func (m *Hello) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Hello) GetType() HelloType {
	if m != nil {
		return m.Type
	}
	return HelloType_NONE
}

func (m *Hello) GetMessages() []string {
	if m != nil {
		return m.Messages
	}
	return nil
}

type ServerError struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Decription           string   `protobuf:"bytes,2,opt,name=decription,proto3" json:"decription,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerError) Reset()         { *m = ServerError{} }
func (m *ServerError) String() string { return proto.CompactTextString(m) }
func (*ServerError) ProtoMessage()    {}
func (*ServerError) Descriptor() ([]byte, []int) {
	return fileDescriptor_sample_bf826917c026f783, []int{2}
}
func (m *ServerError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerError.Unmarshal(m, b)
}
func (m *ServerError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerError.Marshal(b, m, deterministic)
}
func (dst *ServerError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerError.Merge(dst, src)
}
func (m *ServerError) XXX_Size() int {
	return xxx_messageInfo_ServerError.Size(m)
}
func (m *ServerError) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerError.DiscardUnknown(m)
}

var xxx_messageInfo_ServerError proto.InternalMessageInfo

func (m *ServerError) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ServerError) GetDecription() string {
	if m != nil {
		return m.Decription
	}
	return ""
}

type FieldValidationError struct {
	Field                string   `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FieldValidationError) Reset()         { *m = FieldValidationError{} }
func (m *FieldValidationError) String() string { return proto.CompactTextString(m) }
func (*FieldValidationError) ProtoMessage()    {}
func (*FieldValidationError) Descriptor() ([]byte, []int) {
	return fileDescriptor_sample_bf826917c026f783, []int{3}
}
func (m *FieldValidationError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldValidationError.Unmarshal(m, b)
}
func (m *FieldValidationError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldValidationError.Marshal(b, m, deterministic)
}
func (dst *FieldValidationError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldValidationError.Merge(dst, src)
}
func (m *FieldValidationError) XXX_Size() int {
	return xxx_messageInfo_FieldValidationError.Size(m)
}
func (m *FieldValidationError) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldValidationError.DiscardUnknown(m)
}

var xxx_messageInfo_FieldValidationError proto.InternalMessageInfo

func (m *FieldValidationError) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *FieldValidationError) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type ValidationError struct {
	Fields               []*FieldValidationError `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ValidationError) Reset()         { *m = ValidationError{} }
func (m *ValidationError) String() string { return proto.CompactTextString(m) }
func (*ValidationError) ProtoMessage()    {}
func (*ValidationError) Descriptor() ([]byte, []int) {
	return fileDescriptor_sample_bf826917c026f783, []int{4}
}
func (m *ValidationError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidationError.Unmarshal(m, b)
}
func (m *ValidationError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidationError.Marshal(b, m, deterministic)
}
func (dst *ValidationError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidationError.Merge(dst, src)
}
func (m *ValidationError) XXX_Size() int {
	return xxx_messageInfo_ValidationError.Size(m)
}
func (m *ValidationError) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidationError.DiscardUnknown(m)
}

var xxx_messageInfo_ValidationError proto.InternalMessageInfo

func (m *ValidationError) GetFields() []*FieldValidationError {
	if m != nil {
		return m.Fields
	}
	return nil
}

type HelloResponse struct {
	Data *Hello `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// Types that are valid to be assigned to Error:
	//	*HelloResponse_Exception
	//	*HelloResponse_FormError
	Error                isHelloResponse_Error `protobuf_oneof:"error"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *HelloResponse) Reset()         { *m = HelloResponse{} }
func (m *HelloResponse) String() string { return proto.CompactTextString(m) }
func (*HelloResponse) ProtoMessage()    {}
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_sample_bf826917c026f783, []int{5}
}
func (m *HelloResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloResponse.Unmarshal(m, b)
}
func (m *HelloResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloResponse.Marshal(b, m, deterministic)
}
func (dst *HelloResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloResponse.Merge(dst, src)
}
func (m *HelloResponse) XXX_Size() int {
	return xxx_messageInfo_HelloResponse.Size(m)
}
func (m *HelloResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HelloResponse proto.InternalMessageInfo

func (m *HelloResponse) GetData() *Hello {
	if m != nil {
		return m.Data
	}
	return nil
}

type isHelloResponse_Error interface {
	isHelloResponse_Error()
}

type HelloResponse_Exception struct {
	Exception *ServerError `protobuf:"bytes,2,opt,name=exception,proto3,oneof"`
}

type HelloResponse_FormError struct {
	FormError *ValidationError `protobuf:"bytes,3,opt,name=form_error,json=formError,proto3,oneof"`
}

func (*HelloResponse_Exception) isHelloResponse_Error() {}

func (*HelloResponse_FormError) isHelloResponse_Error() {}

func (m *HelloResponse) GetError() isHelloResponse_Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *HelloResponse) GetException() *ServerError {
	if x, ok := m.GetError().(*HelloResponse_Exception); ok {
		return x.Exception
	}
	return nil
}

func (m *HelloResponse) GetFormError() *ValidationError {
	if x, ok := m.GetError().(*HelloResponse_FormError); ok {
		return x.FormError
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*HelloResponse) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _HelloResponse_OneofMarshaler, _HelloResponse_OneofUnmarshaler, _HelloResponse_OneofSizer, []interface{}{
		(*HelloResponse_Exception)(nil),
		(*HelloResponse_FormError)(nil),
	}
}

func _HelloResponse_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*HelloResponse)
	// error
	switch x := m.Error.(type) {
	case *HelloResponse_Exception:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Exception); err != nil {
			return err
		}
	case *HelloResponse_FormError:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.FormError); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("HelloResponse.Error has unexpected type %T", x)
	}
	return nil
}

func _HelloResponse_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*HelloResponse)
	switch tag {
	case 2: // error.exception
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ServerError)
		err := b.DecodeMessage(msg)
		m.Error = &HelloResponse_Exception{msg}
		return true, err
	case 3: // error.form_error
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ValidationError)
		err := b.DecodeMessage(msg)
		m.Error = &HelloResponse_FormError{msg}
		return true, err
	default:
		return false, nil
	}
}

func _HelloResponse_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*HelloResponse)
	// error
	switch x := m.Error.(type) {
	case *HelloResponse_Exception:
		s := proto.Size(x.Exception)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *HelloResponse_FormError:
		s := proto.Size(x.FormError)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_sample_bf826917c026f783, []int{6}
}
func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (dst *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(dst, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*Error)(nil), "sample.Error")
	proto.RegisterType((*Hello)(nil), "sample.Hello")
	proto.RegisterType((*ServerError)(nil), "sample.ServerError")
	proto.RegisterType((*FieldValidationError)(nil), "sample.FieldValidationError")
	proto.RegisterType((*ValidationError)(nil), "sample.ValidationError")
	proto.RegisterType((*HelloResponse)(nil), "sample.HelloResponse")
	proto.RegisterType((*HelloRequest)(nil), "sample.HelloRequest")
	proto.RegisterEnum("sample.HelloType", HelloType_name, HelloType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HelloServiceClient is the client API for HelloService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HelloServiceClient interface {
	Greeting(ctx context.Context, in *Hello, opts ...grpc.CallOption) (*HelloResponse, error)
	SetGreeting(ctx context.Context, in *Hello, opts ...grpc.CallOption) (*HelloResponse, error)
}

type helloServiceClient struct {
	cc *grpc.ClientConn
}

func NewHelloServiceClient(cc *grpc.ClientConn) HelloServiceClient {
	return &helloServiceClient{cc}
}

func (c *helloServiceClient) Greeting(ctx context.Context, in *Hello, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, "/sample.HelloService/Greeting", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helloServiceClient) SetGreeting(ctx context.Context, in *Hello, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, "/sample.HelloService/SetGreeting", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HelloServiceServer is the server API for HelloService service.
type HelloServiceServer interface {
	Greeting(context.Context, *Hello) (*HelloResponse, error)
	SetGreeting(context.Context, *Hello) (*HelloResponse, error)
}

func RegisterHelloServiceServer(s *grpc.Server, srv HelloServiceServer) {
	s.RegisterService(&_HelloService_serviceDesc, srv)
}

func _HelloService_Greeting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Hello)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServiceServer).Greeting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sample.HelloService/Greeting",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServiceServer).Greeting(ctx, req.(*Hello))
	}
	return interceptor(ctx, in, info, handler)
}

func _HelloService_SetGreeting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Hello)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServiceServer).SetGreeting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sample.HelloService/SetGreeting",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServiceServer).SetGreeting(ctx, req.(*Hello))
	}
	return interceptor(ctx, in, info, handler)
}

var _HelloService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sample.HelloService",
	HandlerType: (*HelloServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Greeting",
			Handler:    _HelloService_Greeting_Handler,
		},
		{
			MethodName: "SetGreeting",
			Handler:    _HelloService_SetGreeting_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sample.proto",
}

func init() { proto.RegisterFile("sample.proto", fileDescriptor_sample_bf826917c026f783) }

var fileDescriptor_sample_bf826917c026f783 = []byte{
	// 441 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xad, 0xb1, 0x93, 0xc6, 0xe3, 0xa4, 0xb4, 0x43, 0x11, 0x56, 0x84, 0x2a, 0xb3, 0x08, 0x29,
	0x42, 0xd0, 0x4a, 0x2e, 0x07, 0x8e, 0xb4, 0x52, 0x3f, 0x2e, 0x04, 0x69, 0x41, 0x48, 0x5c, 0xa8,
	0x96, 0x78, 0x6a, 0x2c, 0x39, 0x59, 0x77, 0xd7, 0x20, 0xfa, 0x17, 0xfa, 0x0b, 0xf8, 0x0d, 0xdc,
	0xfb, 0xff, 0xd0, 0x7e, 0xb8, 0x69, 0xaa, 0x5e, 0x7a, 0xdb, 0x79, 0xfb, 0xde, 0xcc, 0x7b, 0xb3,
	0x0b, 0x43, 0x2d, 0xe6, 0x4d, 0x4d, 0xbb, 0x8d, 0x92, 0xad, 0xc4, 0xbe, 0xab, 0xc6, 0x59, 0xa9,
	0x44, 0xf3, 0xf3, 0xa2, 0x7e, 0x4b, 0x45, 0x49, 0x7b, 0xf6, 0x6e, 0xcf, 0x43, 0x8e, 0xc9, 0xde,
	0x40, 0xef, 0x48, 0x29, 0xa9, 0xf0, 0x25, 0x8c, 0xc8, 0x1c, 0xce, 0xe6, 0xa4, 0xb5, 0x28, 0x29,
	0x0d, 0xb2, 0x60, 0x12, 0xf3, 0xa1, 0x05, 0x3f, 0x3a, 0x8c, 0x7d, 0x87, 0xde, 0x29, 0xd5, 0xb5,
	0x44, 0x84, 0x68, 0x21, 0xe6, 0x1d, 0xc9, 0x9e, 0xf1, 0x15, 0x44, 0xed, 0x65, 0x43, 0xe9, 0xa3,
	0x2c, 0x98, 0x6c, 0xe4, 0x5b, 0xbb, 0xde, 0x91, 0x15, 0x7c, 0xb9, 0x6c, 0x88, 0xdb, 0x6b, 0x1c,
	0xc3, 0xc0, 0x8f, 0xd0, 0x69, 0x98, 0x85, 0x93, 0x98, 0xdf, 0xd4, 0xec, 0x00, 0x92, 0xcf, 0xa4,
	0x7e, 0x93, 0x72, 0x9e, 0x10, 0xa2, 0x99, 0x2c, 0xdc, 0x94, 0x1e, 0xb7, 0x67, 0xdc, 0x01, 0x28,
	0x68, 0xa6, 0xaa, 0xa6, 0xad, 0xe4, 0xc2, 0xce, 0x8a, 0xf9, 0x2d, 0x84, 0x1d, 0xc2, 0xf6, 0x71,
	0x45, 0x75, 0xf1, 0x55, 0xd4, 0x55, 0x21, 0x0c, 0xe4, 0x7a, 0x6d, 0x43, 0xef, 0xdc, 0xe0, 0xde,
	0xb2, 0x2b, 0x0c, 0x6a, 0x03, 0xfa, 0x46, 0xae, 0x60, 0x27, 0xf0, 0xf8, 0xae, 0xfc, 0x1d, 0xf4,
	0xad, 0x42, 0xa7, 0x41, 0x16, 0x4e, 0x92, 0xfc, 0x79, 0x17, 0xef, 0xbe, 0x61, 0xdc, 0x73, 0xd9,
	0xbf, 0x00, 0x46, 0x36, 0x3f, 0x27, 0xdd, 0xc8, 0x85, 0x26, 0x7c, 0x01, 0x51, 0x21, 0x5a, 0x61,
	0x5d, 0x24, 0xf9, 0x68, 0x65, 0x49, 0xdc, 0x5e, 0xe1, 0x3e, 0xc4, 0xf4, 0x67, 0x46, 0xcb, 0x80,
	0x49, 0xfe, 0xa4, 0xe3, 0xdd, 0xda, 0xce, 0xe9, 0x1a, 0x5f, 0xf2, 0xf0, 0x3d, 0xc0, 0xb9, 0x54,
	0xf3, 0x33, 0x97, 0x26, 0xb4, 0xaa, 0x67, 0x9d, 0xea, 0x8e, 0x3d, 0xa3, 0x34, 0x64, 0x5b, 0x1c,
	0xae, 0xfb, 0x15, 0x30, 0x06, 0x43, 0xef, 0xf5, 0xe2, 0x17, 0xe9, 0xf6, 0xbe, 0x37, 0x7e, 0xbd,
	0x03, 0xf1, 0xcd, 0x7b, 0xe2, 0x00, 0xa2, 0xe9, 0xa7, 0xe9, 0xd1, 0xe6, 0x1a, 0xae, 0x43, 0x78,
	0x30, 0xfd, 0xb6, 0x19, 0xe4, 0x7f, 0x03, 0xdf, 0xc4, 0x18, 0xad, 0x66, 0x84, 0x1f, 0x60, 0x70,
	0xa2, 0x88, 0xda, 0x6a, 0x51, 0xe2, 0x6a, 0xda, 0xf1, 0xd3, 0xd5, 0xf0, 0x7e, 0x43, 0x6c, 0xe3,
	0xea, 0x3a, 0x05, 0x18, 0x94, 0x9d, 0xea, 0xd8, 0xfc, 0x89, 0xf6, 0x81, 0x4d, 0xb6, 0xae, 0xae,
	0xd3, 0x11, 0x26, 0x7a, 0x29, 0xfc, 0xd1, 0xb7, 0x1f, 0x7e, 0xff, 0x7f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x4e, 0x80, 0xf2, 0x96, 0x2a, 0x03, 0x00, 0x00,
}
