// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common/shared.proto

package common_shared

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/ncrypthic/graphql-grpc-edge/graphql"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Currency int32

const (
	Currency_UNKNOWN Currency = 0
	Currency_USD     Currency = 1
	Currency_IDR     Currency = 2
)

var Currency_name = map[int32]string{
	0: "UNKNOWN",
	1: "USD",
	2: "IDR",
}

var Currency_value = map[string]int32{
	"UNKNOWN": 0,
	"USD":     1,
	"IDR":     2,
}

func (x Currency) String() string {
	return proto.EnumName(Currency_name, int32(x))
}

func (Currency) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_142cd4d48c7dcc7a, []int{0}
}

type Money struct {
	Currency             string   `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	Amount               string   `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Money) Reset()         { *m = Money{} }
func (m *Money) String() string { return proto.CompactTextString(m) }
func (*Money) ProtoMessage()    {}
func (*Money) Descriptor() ([]byte, []int) {
	return fileDescriptor_142cd4d48c7dcc7a, []int{0}
}

func (m *Money) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Money.Unmarshal(m, b)
}
func (m *Money) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Money.Marshal(b, m, deterministic)
}
func (m *Money) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Money.Merge(m, src)
}
func (m *Money) XXX_Size() int {
	return xxx_messageInfo_Money.Size(m)
}
func (m *Money) XXX_DiscardUnknown() {
	xxx_messageInfo_Money.DiscardUnknown(m)
}

var xxx_messageInfo_Money proto.InternalMessageInfo

func (m *Money) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *Money) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func init() {
	proto.RegisterEnum("common.shared.Currency", Currency_name, Currency_value)
	proto.RegisterType((*Money)(nil), "common.shared.Money")
}

func init() {
	proto.RegisterFile("common/shared.proto", fileDescriptor_142cd4d48c7dcc7a)
}

var fileDescriptor_142cd4d48c7dcc7a = []byte{
	// 163 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4e, 0xce, 0xcf, 0xcd,
	0xcd, 0xcf, 0xd3, 0x2f, 0xce, 0x48, 0x2c, 0x4a, 0x4d, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0xe2, 0x85, 0x08, 0xea, 0x41, 0x04, 0xa5, 0xd4, 0xd3, 0x8b, 0x12, 0x0b, 0x32, 0x0a, 0x73, 0x74,
	0xd3, 0x8b, 0x0a, 0x92, 0x75, 0x53, 0x53, 0xd2, 0x53, 0xf5, 0xa1, 0x22, 0x30, 0x1a, 0xa2, 0x4f,
	0xc9, 0x9a, 0x8b, 0xd5, 0x37, 0x3f, 0x2f, 0xb5, 0x52, 0x48, 0x8a, 0x8b, 0x23, 0xb9, 0xb4, 0xa8,
	0x28, 0x35, 0x2f, 0xb9, 0x52, 0x82, 0x51, 0x81, 0x51, 0x83, 0x33, 0x08, 0xce, 0x17, 0x12, 0xe3,
	0x62, 0x4b, 0xcc, 0xcd, 0x2f, 0xcd, 0x2b, 0x91, 0x60, 0x02, 0xcb, 0x40, 0x79, 0x5a, 0x9a, 0x5c,
	0x1c, 0xce, 0x30, 0x35, 0xdc, 0x5c, 0xec, 0xa1, 0x7e, 0xde, 0x7e, 0xfe, 0xe1, 0x7e, 0x02, 0x0c,
	0x42, 0xec, 0x5c, 0xcc, 0xa1, 0xc1, 0x2e, 0x02, 0x8c, 0x20, 0x86, 0xa7, 0x4b, 0x90, 0x00, 0x53,
	0x12, 0x1b, 0xd8, 0x3a, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe7, 0xbf, 0x12, 0x2f, 0xbd,
	0x00, 0x00, 0x00,
}
